# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85031ae3a4eccabac285bd24ee5fab82743e0482c7c077dd0a7d3692e9530b8f25560cc61754cf672529d4d0b06d460c9866a856cc6b9a380c6e91761237f8dc

test:
  secret_key_base: 322f0fc5e49f76ab2a74c5218a0f950b85990033f39cade65b2bdf559fc0d6a51199b1ebc3bcc62bd5dbf8a77606f21034a80a6241e941ee8eb9e84ffd4605e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
